### ISSUE TITLE
suggestion: Get latest Node.js release through GitHub APIs instead of hardcoding URLs.

### ISSUE THREAD

**Issue by ajhalili2006** [Yonle/nodejs-launcher#1]
## Possibly Suggested Implementation

```bash
export NODEJS_CURRENT_RELEASE=$(curl --silent "https://api.github.com/repos/nodejs/node/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
export DOWNLOAD_URL="https://nodejs.org/dist/${NODEJS_CURRENT_RELEASE}/node-${NODEJS_CURRENT_RELEASE}-linux-x64.tar.xz"
```

## Alternative Options

* If hardcoding download links are still preferred, maybe we need to automate it with GitHub Actions.
* Use `git ls-remote --refs --sort="version:refname" --tags https://github.com/nodejs/node | cut -d/ -f3-|tail -n1`, assuming Relpit containers has Git preinstalled.

**Comment by ajhalili2006** [comment]
The stuff in both sections is from https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c (including some comments) by the way.

**Comment by Yonle** [comment]
I see. You may open Pull Request if you want.

**Comment by Yonle** [comment]
Thanks for the suggestion.
